name: Build and Upload APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK and Upload to App Directory
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17' # Match your project's JDK version

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Copy APK to App Directory
      run: |
        mkdir -p app
        cp app/build/outputs/apk/debug/app-debug.apk app/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/app-debug.apk
